title:            "金戈铁马"
description:      "每天醒来，敲醒自己的不是钟声，而是梦想"
logo:             omikron.png
disqus_shortname:
duoshuo_shortname:  lonpo
# Assign a default image for your site's header and footer
default_bg:       /images/bg2.jpg
search:           true
share:            true
# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime:         true
# Specify the average Words per minute. If not defined, 180 will be used
wpm:				      200
# Turn on or off the fin animations in the header and footer
triangleheader:		true
animated_fins:	  true
# Specify the fin color in RGB value
fin_color:        "255,255,255"

# Owner/author information
owner:
  name:           "lonpo"
  avatar:         logo.jpg
  email:          jinking@leweg.com
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    "每天醒来，敲醒自己的不是钟声，而是梦想"
  # Social networking links used in footer. Update and remove as you like.
  twitter:        lonpo
  facebook:       lonpo
  github:         lonpo
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  weibo: 1662705782
  # For Google Authorship https://plus.google.com/authorship
google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-47369838-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Categories
    url: /categories
    icon: bars
  - title: Tags
    url: /tags
    icon: tags
  - title: Guestbook
    url: /guestbook
    icon: comments
  - title: Links
    url:   /links
    icon: link
  - title: About
    url: /about
    icon: user

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir: 	  ./_data
includes_dir: ./_includes
collections:  null

# Handling Reading
safe:         true
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
gems:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
whitelist:
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "<!--more-->"
incremental:  false
gist:
   noscript: false

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site

# Backwards-compatibility
relative_permalinks: false

# Outputting
permalink:     date
paginate: 6
paginate_path: /page:num
timezone:      Asia/Shanghai

quiet:    false
defaults: []

# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: []

github: [metadata]
kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  input:          GFM
  hard_wrap: 	  false
  
  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

redcloth:
  hard_breaks: true

sass:
    sass_dir: _sass
    style: :compressed
